composition:
  name: KVQueue
systems:
  queue:
    type: Kafka
    delivery: exactly_once
    ordering: partition_level
    messaging_model: pub_sub
    max_size: 10000
  kv:
    type: BaseKV
    consistency: strong
    conditional_writes: true
    idempotent_writes: true
    replicas: false
    max_size: 100
