composition:
  name: KVQueue
systems:
  queue:
    type: ActiveMQ
    delivery: at_least_once
    ordering: queue_level
    messaging_model: pub_sub
    max_size: 10000
  kv:
    type: BaseKV
    consistency: strong
    conditional_writes: true
    idempotent_writes: true
    replicas: true
    max_size: 100
