# TODO: read capabilities from config and generate systems accordingly
composition:
  name: KVQueue
systems:
  queue:
    type: BaseQueue
    delivery: at_least_once
    max_size: 100

  kv:
    type: BaseKV
    consistency: strong
    conditional_writes: true
    idempotent_writes: true
    replicas: false
    max_size: 100